### ISSUE TITLE
What are the disease conditions in RxRx19b dataset?

### ISSUE THREAD

**Issue by Sadegh-Saberian** [recursionpharma/rxrx-datasets#2]
Hi,
I was checking the dataset and saw this in the webpage:
`856 small molecules at 4-6 concentrations in three COVID-19-associated cytokine storm conditions (severe storm, healthy, and no cytokines)`

but when I checked the metadata file, there are only two actual conditions: healthy and storm-severe. There is also 264 entries with no disease condition. Could you please explain what am I missing here. 

Thanks!

**Comment by ihaque** [comment]
Hi Sadegh,

`healthy` and `storm-severe` are two different formulations of cytokine cocktails (the analysis in the associated preprint describes compound rescure from the `storm-severe` state to the `healthy` state). The entries without disease condition are the third experimental condition: cells without any cytokines applied. These were not used in the preprint but are included for completeness.

**Comment by ihaque** [comment]
(I've updated the README on GitHub to reflect this, and we'll incorporate that README change into the downloadable files at a later date.)
