### ISSUE TITLE
channels and stains mapping

### ISSUE THREAD

**Issue by Sadegh-Saberian** [recursionpharma/rxrx-datasets#4]
Hello,

I could not find the mapping between the channel numbers and the stains used in the imaging for RxRx19b dataset in the paper or on github. could you please let me know the mapping, eg. channel 1 is Hoechst? thanks.

**Comment by ihaque** [comment]
Hi Sadegh,

In RxRx19b, you should have

1:hoechst(nuclear)
2:conA(ER)
3:phalloidin(actin)
4:syto14(rna)
5:mitotracker (mitochondria)
6:WGA(membranes, golgi)

RxRx19a did not have MitoTracker, so in that dataset channel 5 is WGA and channel 6 does not exist.

(Nice MLCB talk, by the way!)

**Comment by Sadegh-Saberian** [comment]
Hello,

I get it, thanks!

(Thank you! :))
