### ISSUE TITLE
download failure of RxRx3

### ISSUE THREAD

**Issue by liujunhongznn** [recursionpharma/rxrx-datasets#8]
I have tried to download RxRx3/MolRec but failed, the hint is 403 forbidden error as follow:
<img width="603" alt="截屏2023-05-22 下午3 41 42" src="https://github.com/recursionpharma/rxrx-datasets/assets/58112580/c8ac2697-afa2-482c-abd5-217116acedf6">

how to deal with it? thanks alot!

**Comment by ihaque** [comment]
Hi @liujunhongznn - unfortunately at this time RxRx3 and MolRec are not accessible in certain geographic regions. We encourage you to take a look at our other datasets, RxRx1, 2, 19a, and 19b, which may be more accessible.
